version: 2.1
jobs:
  test:
    docker:
      - image: golang:1.12-alpine
        environment:
          GO111MODULE=on
    working_directory: /var/repo
    steps:
      - checkout
      - run: go test
workflows:
  version: 2
  test:
    jobs:
      - test